version: "3.8"

services:
  keylogger-server:
    build: .
    ports:
      - "5000:5000"
      - "443:443"
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
